// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIDevSecOpsScallingSDD.Context;

#nullable disable

namespace WebAPIDevSecOpsScallingSDD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005034005_UniqueConstraints")]
    partial class UniqueConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.CliCliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("strCorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("strCreadoPorUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strDireccionCliente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("strNombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("strNumeroTelefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("CliCliente");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.EmpCatTipoEmpleado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("strDescripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("strValor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("EmpCatTipoEmpleado");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.EmpEmpleado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("idEmpCatTipoEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("strAMaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strAPaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strCURP")
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.Property<string>("strNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("idEmpCatTipoEmpleado");

                    b.ToTable("EmpEmpleado");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.ProProducto", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("decPrecio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("intNumeroExistencia")
                        .HasColumnType("int");

                    b.Property<string>("strCreadoPorUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strDescripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("strNombreProducto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strURLImagen")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("id");

                    b.ToTable("ProProducto");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.SegRefreshToken", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("dteCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dteExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dteRevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("idSegUsuario")
                        .HasColumnType("int");

                    b.Property<string>("strReplacedByTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("strTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("id");

                    b.HasIndex("idSegUsuario");

                    b.ToTable("SegRefreshToken");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.SegUsuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("bln2FAHabilitado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("dteFechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("str2FASecreto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("strCorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strPWD")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("id");

                    b.ToTable("SegUsuario");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenCatEstado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("strDescripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("strValor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("VenCatEstado");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenPedido", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LegacyVentaId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("decTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dteFechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCliCliente")
                        .HasColumnType("int");

                    b.Property<string>("strEstadoSaga")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strMotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.HasIndex("idCliCliente");

                    b.ToTable("VenPedido");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenPedidoDetalle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("decPrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("idProProducto")
                        .HasColumnType("int");

                    b.Property<Guid>("idVenPedido")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("intCantidad")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idProProducto");

                    b.HasIndex("idVenPedido");

                    b.ToTable("VenPedidoDetalle");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenPedidoFactura", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("decTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dteFechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("idVenPedido")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("strFolioFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("strRFC")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("id");

                    b.HasIndex("idVenPedido");

                    b.HasIndex("strFolioFactura")
                        .IsUnique();

                    b.ToTable("VenPedidoFactura");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenPedidoPago", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("decMonto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("dteFechaPago")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("idVenPedido")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("strEstado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("strIdTransaccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("strMetodoPago")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("idVenPedido");

                    b.HasIndex("strIdTransaccion")
                        .IsUnique()
                        .HasFilter("[strIdTransaccion] IS NOT NULL");

                    b.ToTable("VenPedidoPago");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenVenta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("dteFechaHoraCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCliCliente")
                        .HasColumnType("int");

                    b.Property<int>("idSegUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idVenCatEstado")
                        .HasColumnType("int");

                    b.Property<string>("strClaveVenta")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.HasIndex("idCliCliente");

                    b.HasIndex("idSegUsuario");

                    b.HasIndex("idVenCatEstado");

                    b.ToTable("VenVenta");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenVentaDetalle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("decTotalVenta")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("idProProducto")
                        .HasColumnType("int");

                    b.Property<int>("idVenVenta")
                        .HasColumnType("int");

                    b.Property<int>("intPiezaVenta")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("idProProducto");

                    b.HasIndex("idVenVenta");

                    b.ToTable("VenVentaDetalle");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.EmpEmpleado", b =>
                {
                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.EmpCatTipoEmpleado", "EmpCatTipoEmpleado")
                        .WithMany()
                        .HasForeignKey("idEmpCatTipoEmpleado");

                    b.Navigation("EmpCatTipoEmpleado");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.SegRefreshToken", b =>
                {
                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.SegUsuario", "SegUsuario")
                        .WithMany()
                        .HasForeignKey("idSegUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SegUsuario");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenPedido", b =>
                {
                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.CliCliente", "CliCliente")
                        .WithMany()
                        .HasForeignKey("idCliCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CliCliente");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenPedidoDetalle", b =>
                {
                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.ProProducto", "ProProducto")
                        .WithMany()
                        .HasForeignKey("idProProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.VenPedido", "VenPedido")
                        .WithMany("Detalles")
                        .HasForeignKey("idVenPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProProducto");

                    b.Navigation("VenPedido");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenPedidoFactura", b =>
                {
                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.VenPedido", "VenPedido")
                        .WithMany("Facturas")
                        .HasForeignKey("idVenPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VenPedido");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenPedidoPago", b =>
                {
                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.VenPedido", "VenPedido")
                        .WithMany("Pagos")
                        .HasForeignKey("idVenPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VenPedido");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenVenta", b =>
                {
                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.CliCliente", "CliCliente")
                        .WithMany()
                        .HasForeignKey("idCliCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.SegUsuario", "SegUsuario")
                        .WithMany()
                        .HasForeignKey("idSegUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.VenCatEstado", "VenCatEstado")
                        .WithMany()
                        .HasForeignKey("idVenCatEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CliCliente");

                    b.Navigation("SegUsuario");

                    b.Navigation("VenCatEstado");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenVentaDetalle", b =>
                {
                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.ProProducto", "ProProducto")
                        .WithMany()
                        .HasForeignKey("idProProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAPIDevSecOpsScallingSDD.Models.VenVenta", "VenVenta")
                        .WithMany()
                        .HasForeignKey("idVenVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProProducto");

                    b.Navigation("VenVenta");
                });

            modelBuilder.Entity("WebAPIDevSecOpsScallingSDD.Models.VenPedido", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Facturas");

                    b.Navigation("Pagos");
                });
#pragma warning restore 612, 618
        }
    }
}
